_homepage:
    path:     /hello/{name}
    defaults: { _controller: WillothewispGuestbookBundle:Default:index }

_posts:
    path: /
    defaults: { _controller: WillothewispGuestbookBundle:Post:list }
