parameters:
    post.repository: WillothewispGuestbookBundle:Post
    post.timer: Willothewisp\Bundle\GuestbookBundle\PostTimer\PostTimer

services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    willothewisp_guestbook.post.repository:
        class: Willothewisp\Bundle\GuestbookBundle\Entity\PostRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments:
            - %post.repository%

    willothewisp_guestbook_post.timer.post.timer:
        class: %post.timer%

    willothewisp.socialBarHelper:
        class : Willothewisp\Bundle\GuestbookBundle\Templating\Helper\SocialBarHelper
        tags :
          - {name : 'templating.helper', alias : 'social-buttons'}
        arguments : [ @templating ]

    twig.extension.willothewisp_social_bar:
        class: Willothewisp\Bundle\GuestbookBundle\Twig\Extensions\WillothewispTwigSocialBar
        tags:
            - { name: 'twig.extension' }
        arguments : [ @service_container ]


#    willothewisp_guestbook.example:
#        class: Willothewisp\Bundle\GuestbookBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
