services:

  twig.extension.text:
           class: Twig_Extensions_Extension_Text
           tags:
               - { name: twig.extension }
#    willothewisp_guestbook.example:
#        class: Willothewisp\Bundle\GuestbookBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
