post:
    path:     /
    defaults: { _controller: "WillothewispGuestbookBundle:Post:index" }

post_show:
    path:     /{id}/show
    defaults: { _controller: "WillothewispGuestbookBundle:Post:show" }
    requirements:
         id: \d+

post_show_by_domain:
    path: /{url}/post
    defaults: { _controller: "WillothewispGuestbookBundle:Post:postsAssociatedWithDomain" }
    requirements:
        url: ^(\w+://)?([^/]+)

post_show_by_author:
    path: /{slug}/posts
    defaults: { _controller: "WillothewispGuestbookBundle:Post:postsAssociatedWithAuthor" }


post_new:
    path:     /new
    defaults: { _controller: "WillothewispGuestbookBundle:Post:new" }

post_create:
    path:     /create
    defaults: { _controller: "WillothewispGuestbookBundle:Post:create" }
    requirements: { _method: post }

post_edit:
    path:     /{id}/edit
    defaults: { _controller: "WillothewispGuestbookBundle:Post:edit" }

post_update:
    path:     /{id}/update
    defaults: { _controller: "WillothewispGuestbookBundle:Post:update" }
    requirements: { _method: post|put }

post_delete:
    path:     /{id}/delete
    defaults: { _controller: "WillothewispGuestbookBundle:Post:delete" }
    requirements: { _method: post|delete }
