<?php

namespace Willothewisp\Bundle\GuestbookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function findNewest()
    {
        return $this->createQueryBuilder('p')
            ->orderBy('p.createdAt', 'DESC')
            ->getQuery()
            ->getResult()
            ;
    }

    public function findPostsAssociatedWithAuthor($author)
    {
        return $this->createQueryBuilder('p')
            ->where('p.author = :author')
            ->setParameter('author', $author)
            ->getQuery()
            ->getResult()
            ;
    }

    public function findPostsAssociatedWithDomain($url)
    {
        return $this->createQueryBuilder('p')
            ->where('p.url = :url')
            ->setParameter('url', $url)
            ->getQuery()
            ->getResult()
            ;
    }

//    public function findOneNewest()
//    {
//        return $this->createQueryBuilder('p')
//            ->
//    }
}
